// Code generated by MockGen. DO NOT EDIT.
// Source: rdma_provider.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_rdma_provider.go -source rdma_provider.go
//

// Package mock_host is a generated GoMock package.
package mock_host

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRdmaProvider is a mock of RdmaProvider interface.
type MockRdmaProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRdmaProviderMockRecorder
	isgomock struct{}
}

// MockRdmaProviderMockRecorder is the mock recorder for MockRdmaProvider.
type MockRdmaProviderMockRecorder struct {
	mock *MockRdmaProvider
}

// NewMockRdmaProvider creates a new mock instance.
func NewMockRdmaProvider(ctrl *gomock.Controller) *MockRdmaProvider {
	mock := &MockRdmaProvider{ctrl: ctrl}
	mock.recorder = &MockRdmaProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRdmaProvider) EXPECT() *MockRdmaProviderMockRecorder {
	return m.recorder
}

// GetRdmaCharDevices mocks base method.
func (m *MockRdmaProvider) GetRdmaCharDevices(rdmaDeviceName string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRdmaCharDevices", rdmaDeviceName)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRdmaCharDevices indicates an expected call of GetRdmaCharDevices.
func (mr *MockRdmaProviderMockRecorder) GetRdmaCharDevices(rdmaDeviceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRdmaCharDevices", reflect.TypeOf((*MockRdmaProvider)(nil).GetRdmaCharDevices), rdmaDeviceName)
}

// GetRdmaDevicesForPcidev mocks base method.
func (m *MockRdmaProvider) GetRdmaDevicesForPcidev(pciAddr string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRdmaDevicesForPcidev", pciAddr)
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetRdmaDevicesForPcidev indicates an expected call of GetRdmaDevicesForPcidev.
func (mr *MockRdmaProviderMockRecorder) GetRdmaDevicesForPcidev(pciAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRdmaDevicesForPcidev", reflect.TypeOf((*MockRdmaProvider)(nil).GetRdmaDevicesForPcidev), pciAddr)
}
