// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/host/netlink_ops.go
//
// Generated by this command:
//
//	mockgen -destination pkg/host/mock/mock_netlink_ops.go -source pkg/host/netlink_ops.go
//

// Package mock_host is a generated GoMock package.
package mock_host

import (
	reflect "reflect"

	netlink "github.com/vishvananda/netlink"
	gomock "go.uber.org/mock/gomock"
)

// MockNetlinkOps is a mock of NetlinkOps interface.
type MockNetlinkOps struct {
	ctrl     *gomock.Controller
	recorder *MockNetlinkOpsMockRecorder
	isgomock struct{}
}

// MockNetlinkOpsMockRecorder is the mock recorder for MockNetlinkOps.
type MockNetlinkOpsMockRecorder struct {
	mock *MockNetlinkOps
}

// NewMockNetlinkOps creates a new mock instance.
func NewMockNetlinkOps(ctrl *gomock.Controller) *MockNetlinkOps {
	mock := &MockNetlinkOps{ctrl: ctrl}
	mock.recorder = &MockNetlinkOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetlinkOps) EXPECT() *MockNetlinkOpsMockRecorder {
	return m.recorder
}

// DevLinkGetDeviceByName mocks base method.
func (m *MockNetlinkOps) DevLinkGetDeviceByName(bus, device string) (*netlink.DevlinkDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DevLinkGetDeviceByName", bus, device)
	ret0, _ := ret[0].(*netlink.DevlinkDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DevLinkGetDeviceByName indicates an expected call of DevLinkGetDeviceByName.
func (mr *MockNetlinkOpsMockRecorder) DevLinkGetDeviceByName(bus, device any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevLinkGetDeviceByName", reflect.TypeOf((*MockNetlinkOps)(nil).DevLinkGetDeviceByName), bus, device)
}
