// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/devicestate (interfaces: DeviceState)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_devicestate.go -package=mock github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/devicestate DeviceState
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	types "github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/types"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/resource/v1"
)

// MockDeviceState is a mock of DeviceState interface.
type MockDeviceState struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStateMockRecorder
	isgomock struct{}
}

// MockDeviceStateMockRecorder is the mock recorder for MockDeviceState.
type MockDeviceStateMockRecorder struct {
	mock *MockDeviceState
}

// NewMockDeviceState creates a new mock instance.
func NewMockDeviceState(ctrl *gomock.Controller) *MockDeviceState {
	mock := &MockDeviceState{ctrl: ctrl}
	mock.recorder = &MockDeviceStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceState) EXPECT() *MockDeviceStateMockRecorder {
	return m.recorder
}

// GetAdvertisedDevices mocks base method.
func (m *MockDeviceState) GetAdvertisedDevices() types.AllocatableDevices {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertisedDevices")
	ret0, _ := ret[0].(types.AllocatableDevices)
	return ret0
}

// GetAdvertisedDevices indicates an expected call of GetAdvertisedDevices.
func (mr *MockDeviceStateMockRecorder) GetAdvertisedDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertisedDevices", reflect.TypeOf((*MockDeviceState)(nil).GetAdvertisedDevices))
}

// GetAllocatableDevices mocks base method.
func (m *MockDeviceState) GetAllocatableDevices() types.AllocatableDevices {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocatableDevices")
	ret0, _ := ret[0].(types.AllocatableDevices)
	return ret0
}

// GetAllocatableDevices indicates an expected call of GetAllocatableDevices.
func (mr *MockDeviceStateMockRecorder) GetAllocatableDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocatableDevices", reflect.TypeOf((*MockDeviceState)(nil).GetAllocatableDevices))
}

// UpdatePolicyDevices mocks base method.
func (m *MockDeviceState) UpdatePolicyDevices(ctx context.Context, policyDevices map[string]map[v1.QualifiedName]v1.DeviceAttribute) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicyDevices", ctx, policyDevices)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePolicyDevices indicates an expected call of UpdatePolicyDevices.
func (mr *MockDeviceStateMockRecorder) UpdatePolicyDevices(ctx, policyDevices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicyDevices", reflect.TypeOf((*MockDeviceState)(nil).UpdatePolicyDevices), ctx, policyDevices)
}
