// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/devicestate (interfaces: DeviceState)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_devicestate.go -package=mock github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/devicestate DeviceState
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	types "github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceState is a mock of DeviceState interface.
type MockDeviceState struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStateMockRecorder
	isgomock struct{}
}

// MockDeviceStateMockRecorder is the mock recorder for MockDeviceState.
type MockDeviceStateMockRecorder struct {
	mock *MockDeviceState
}

// NewMockDeviceState creates a new mock instance.
func NewMockDeviceState(ctrl *gomock.Controller) *MockDeviceState {
	mock := &MockDeviceState{ctrl: ctrl}
	mock.recorder = &MockDeviceStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceState) EXPECT() *MockDeviceStateMockRecorder {
	return m.recorder
}

// GetAllocatableDevices mocks base method.
func (m *MockDeviceState) GetAllocatableDevices() types.AllocatableDevices {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllocatableDevices")
	ret0, _ := ret[0].(types.AllocatableDevices)
	return ret0
}

// GetAllocatableDevices indicates an expected call of GetAllocatableDevices.
func (mr *MockDeviceStateMockRecorder) GetAllocatableDevices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllocatableDevices", reflect.TypeOf((*MockDeviceState)(nil).GetAllocatableDevices))
}

// UpdateDeviceResourceNames mocks base method.
func (m *MockDeviceState) UpdateDeviceResourceNames(ctx context.Context, deviceResourceMap map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceResourceNames", ctx, deviceResourceMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceResourceNames indicates an expected call of UpdateDeviceResourceNames.
func (mr *MockDeviceStateMockRecorder) UpdateDeviceResourceNames(ctx, deviceResourceMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceResourceNames", reflect.TypeOf((*MockDeviceState)(nil).UpdateDeviceResourceNames), ctx, deviceResourceMap)
}
