// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -destination mock/mock_cni.go -package mock -source interface.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	api "github.com/containerd/nri/pkg/api"
	types "github.com/k8snetworkplumbingwg/dra-driver-sriov/pkg/types"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/resource/v1"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// AttachNetwork mocks base method.
func (m *MockInterface) AttachNetwork(ctx context.Context, pod *api.PodSandbox, podNetworkNamespace string, deviceConfig *types.PreparedDevice) (*v1.NetworkDeviceData, map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachNetwork", ctx, pod, podNetworkNamespace, deviceConfig)
	ret0, _ := ret[0].(*v1.NetworkDeviceData)
	ret1, _ := ret[1].(map[string]any)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AttachNetwork indicates an expected call of AttachNetwork.
func (mr *MockInterfaceMockRecorder) AttachNetwork(ctx, pod, podNetworkNamespace, deviceConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachNetwork", reflect.TypeOf((*MockInterface)(nil).AttachNetwork), ctx, pod, podNetworkNamespace, deviceConfig)
}

// DetachNetwork mocks base method.
func (m *MockInterface) DetachNetwork(ctx context.Context, pod *api.PodSandbox, podNetworkNamespace string, deviceConfig *types.PreparedDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachNetwork", ctx, pod, podNetworkNamespace, deviceConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// DetachNetwork indicates an expected call of DetachNetwork.
func (mr *MockInterfaceMockRecorder) DetachNetwork(ctx, pod, podNetworkNamespace, deviceConfig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachNetwork", reflect.TypeOf((*MockInterface)(nil).DetachNetwork), ctx, pod, podNetworkNamespace, deviceConfig)
}
